export const vignettes = [
    {
        id:  "WaylandTheater",
        imageUrl: "/projects/theroadlessboring/images/WaylandTheater1.jpg",
        alt: "a high school theater basement, covered in graffiti",
        url: "WaylandTheater",
        title: "Signatures Like These",
        caption: "Start Here",
        description: ["This picture is the room beneath my high school's theater, its walls covered in the signatures of former students. Thousands of names, layered on top of one another, some dating back to the 1960s (on a campus that has been around since 1855). At some point, I added mine, signed my name on the wall and walked away without giving it much thought.",
            "Nearly thirty years later, I returned to that room and found my signature still there. Seeing it again pulled me back in time: the hours spent in the theater, the people I knew, the version of myself who stood in that room and left a small mark without realizing how much it would come to mean. What stayed with me most wasn't just the personal memories elicited by finding my own name, but the realization that every signature on those walls carried the same weight; each one was tied to a life, a set of memories, a time that mattered deeply to someone.",
            "That's how I experience the places I'm drawn to when I travel. Every place holds millions of invisible signatures. You won't usually find them physically written on walls, but they're there: in kitchens where families gathered, in roadside attractions built from someone's strange idea, in ordinary rooms that once held countless seemingly mundane conversations.",
            "Places are never just locations; they are quiet archives of the people who passed through them. 'The Road Less Boring' is a visual scrapbook of those hidden signatures. It's not a travel log or an itinerary. It's an exploration of places as containers of memory, history, humor, and humanity. The images invite you to slow down, look closer, and imagine the lives that unfolded there."],
        town: "Beaver Dam",
        state: "Wisconsin",
        country: "United States of America",
        lat: "43.458",
        lng:"-88.827",
        tags: "",
        type: "origin",
        revealed: false
    },
     {
        id:  "DoverHouse",
        imageUrl: "/projects/theroadlessboring/images/DoverHouse.jpg",
        url: "DoverHouse",
        alt: "Bright blue house with porch",
        title: "The Dover House",
        caption: "",
        description: ["This house was built in 1880. In the years since, I have no idea how many families and stories have passed through it. For me, it holds the weight of one family and one moment.", 
            "I found it while doing genealogy research on my ancestors. My grandfather was an only child, so it stopped me short when I came across a death certificate for a sibling I'd never heard of. The place of death was listed as this address.", 
            "My great-grandparents were both born deaf. We don't know how they met. He was from Massachusetts and she from New Hampshire. I imagine that navigating a hearing world in the early 1900s gave them a shared language of experience long before they shared a last name. They were married in Massachusetts in 1916.",
            "Five years later, my grandfather was born. That stretch of time raises questions, especially for a young couple in that era. Then I found the record: a stillborn boy, born and died on June 1, 1918, in this house.",
            "I decided to visit it while on a vacation to New England. As soon as I pulled up, these ancestors stopped being abstractions. This wasn’t just a branch on a family tree. It was a place, a day, a loss. I don't know what brought them to this house. I can only guess they were staying with my great-grandmother's relatives, whose family was from Dover, while her husband's family remained in Massachusetts.",
            "When I stood in front of this house, I couldn't stop thinking about the grief that must have lived here for that brief time. How long they may have waited for a child, only to lose one in this very place. And how, years later, the birth of my grandfather must have carried a depth of meaning shaped by that loss.",
            "This is what draws me to places like this. Houses, streets, and ordinary buildings are filled with invisible signatures. Moments of love, hope, and heartbreak that never make it into history books. This house holds one of those signatures quietly, whether anyone passing by knows it or not."
        ],
        town: "Dover",
        state: "New Hampshire",
        country: "United States of America",
        lat: "43.201",
        lng:"-70.874",
        type: "historical",
        tags: "",
        revealed: false
    },
        {
        id:  "LachoEarthOven",
        imageUrl: "/projects/theroadlessboring/images/LachoEarthOven.jpg",
        alt: "A deep hole in the ground with stone walls",
        url: "LachoEarthOven",
        title: "Stone Oven, Stories of Independence",
        caption: "",
        description: [],
        town: "Labadee",
        state: "",
        country: "Haiti",
        lat: "19.774",
        lng:"-72.243",
        tags: "",
        type: "historical",
        revealed: false
    },
    {
        id:  "ElvisPlayground",
        imageUrl: "/projects/theroadlessboring/images/ElvisPlayground.jpg",
        alt: "a metal playground",
        url: "ElvisPlayground",
        title: "Lisa Marie's playset",
        caption: "",
        description: [],
        town: "Memphis",
        state: "Tennessee",
        country: "United States of America",
        lat: "35.046",
        lng:"-90.023",
        tags: "",
        type: "historical",
        revealed: false
    },
       {
        id:  "HooverDam",
        imageUrl: "/projects/theroadlessboring/images/HooverDam.jpg",
        alt: "A long metal staircase",
        url: "HooverDam",
        title: "Emergency Exit",
        caption: "",
        description: [],
        town: "Boulder City",
        state: "Nevada",
        country: "United States of America",
        lat: "36.016",
        lng:"-114.738",
        tags: "",
        type: "historical",
        revealed: false
    },
  
     {
        id:  "LighthouseDanger",
        imageUrl: "/projects/theroadlessboring/images/LighthouseDanger.jpg",
        alt: "The inside of the top of a lighthouse",
        url: "LighthouseDanger",
        title: "Minnesota's oldest operating lighthouse",
        caption: "",
        description: [],
        town: "Two Harbors",
        state: "Minnesota",
        country: "United States of America",
        lat: "47.014",
        lng:"-91.664",
        tags: "",
        type: "historical",
        revealed: false
    },
     {
        id:  "JudyGarlandBirthplace",
        imageUrl: "/projects/theroadlessboring/images/JudyGarlandBirthplace.jpg",
        alt: "",
        url: "JudyGarlandBirthplace",
        title: "The Gumm House",
        caption: "",
        description: [],
        town: "Grand Rapids",
        state: "Minnesota",
        country: "United States of America",
        lat: "47.206",
        lng:"-93.530",
        tags: "",
        type: "historical",
        revealed: false
    },
    {
        id:  "RaptorRanch",
        imageUrl: "/projects/theroadlessboring/images/RaptorRanch.jpg",
        alt: "A pink house from the Flintstones",
        url: "RaptorRanch",
        title: "Bedrock City",
        caption: "",
        description: [],
        town: "Valle",
        state: "Arizona",
        country: "United States of America",
        lat: "35.655",
        lng:"-112.141",
        tags: "",
        type: "historical",
        revealed: false
    },
 
    {
        id:  "ElvisKitchen",
        imageUrl: "/projects/theroadlessboring/images/ElvisKitchen.jpg",
        alt: "a retro kitchen with carpet",
        url: "ElvisKitchen",
        title: "Elvis' Kitchen",
        caption: "",
        description: [],
        town: "Memphis",
        state: "Tennessee",
        country: "United States of America",
        tags: "",
        lat: "35.046",
        lng:"-90.023",
        type: "historical",
        revealed: false
    },
     {
        id:  "ArtAlley",
        imageUrl: "/projects/theroadlessboring/images/ArtAlley.jpg",
        url: "ArtAlley",
        alt: "An alleyway covered in graffiti",
        title: "Art Alley",
        caption: "",
        description: ["this is yet another test"],
        town: "Rapid City",
        state: "South Dakota",
        country: "United States of America",
        lat: "44.081",
        lng:"-103.229",
        type: "quirky",
        tags: "",
        revealed: false
    },
     {
        id:  "LucyHouse",
        imageUrl: "/projects/theroadlessboring/images/LucyHouse.jpg",
        url: "LucyHouse",
        alt: "An alleyway covered in graffiti",
        title: "Lucy's Childhood Home",
        caption: "",
        description: [""],
        town: "Celoron",
        state: "New York",
        country: "United States of America",
        lat: "42.103",
        lng:"-79.287",
        type: "historical",
        tags: "",
        revealed: false
    },
     {
        id:  "BirdcageStairs",
        imageUrl: "/projects/theroadlessboring/images/BirdcageStairs.jpg",
        url: "BirdcageStairs",
        alt: "Narrow stairs leading to a small room",
        title: "The Birdcage Theater",
        caption: "",
        description: [""],
        town: "Tombstone",
        state: "Arizona",
        country: "United States of America",
        lat: "31.712",
        lng:"-110.065",
        type: "historical",
        tags: "",
        revealed: false
    },
    {
        id:  "Wupatki",
        imageUrl: "/projects/theroadlessboring/images/Wupatki.jpg",
        url: "Wupatki",
        alt: "Small brick walls in the desert",
        title: "Citadel Pueblo - A Home Among Many",
        caption: "",
        description: [""],
        town: "Flagstaff",
        state: "Arizona",
        country: "United States of America",
        lat: "35.566",
        lng:"-111.471",
        type: "historical",
        tags: "",
        revealed: false
    }

]