export const vignettes = [
    {
        id:  "WaylandTheater",
        imageUrl: "/projects/theroadlessboring/images/WaylandTheater1.jpg",
        alt: "a high school theater basement, covered in graffiti",
        url: "WaylandTheater",
        title: "Signatures Like These",
        caption: "Start Here",
        description: ["In my high school, there was a room beneath the theater whose walls were covered in the signatures of former students. Thousands of names, layered on top of one another, some dating back to the 1960s. At some point, I added mine, signed my name on the wall and walked away without giving it much thought.",
            "Nearly thirty years later, I returned to that room and found my signature still there. Seeing it again pulled me back in time: the hours spent in the theater, the people I knew, the version of myself who stood in that room and left a small mark without realizing how much it would come to mean. What stayed with me most wasn't just the memory of my own name, but the realization that every signature on those walls carried the same weight; each one was tied to a life, a set of memories, a time that mattered deeply to someone.",
            "That's how I experience the places I'm drawn to when I travel. Every place holds millions of invisible signatures. They aren't written on walls, but they're there: in kitchens where families gathered, in roadside attractions built from someone's strange idea, in ordinary rooms that once held hundreds of seemingly mundane conversations.",
            "Places are never just locations; they are quiet archives of the people who passed through them. 'The Road Less Boring' is a visual scrapbook of those hidden signatures. It's not a travel log or an itinerary. It's an exploration of places as containers of memory, history, humor, and humanity. The images invite you to slow down, look closer, and imagine the lives that unfolded there long before you arrived."],
        town: "Beaver Dam",
        state: "Wisconsin",
        country: "United States of America",
        tags: "",
        type: "origin",
        revealed: false
    },
    {
        id:  "ElvisPlayground",
        imageUrl: "/projects/theroadlessboring/images/ElvisPlayground.jpg",
        alt: "a metal playground",
        url: "ElvisPlayground",
        title: "some title about this picture",
        caption: "",
        description: ["this is a test"],
        town: "Memphis",
        state: "Tennessee",
        country: "United States of America",
        tags: "music",
        type: "historical",
        revealed: false
    },
    {
        id:  "ElvisKitchen",
        imageUrl: "/projects/theroadlessboring/images/ElvisKitchen.jpg",
        alt: "a retro kitchen with carpet",
        url: "ElvisKitchen",
        title: "Elvis' Kitchen",
        caption: "",
        description: ["this is another test"],
        town: "Memphis",
        state: "Tennessee",
        country: "United States of America",
        tags: "music, food",
        type: "historical",
        revealed: false
    },
     {
        id:  "ArtAlley",
        imageUrl: "/projects/theroadlessboring/images/ArtAlley.jpg",
        url: "ArtAlley",
        alt: "An alleyway covered in graffiti",
        title: "some title about this picture",
        caption: "",
        description: ["this is yet another test"],
        town: "Grand Rapids",
        state: "South Dakota",
        country: "United States of America",
        type: "quirky",
        tags: "food",
        revealed: false
    }

]